// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	ReleaseYear int32          `json:"release_year"`
	Genre       []string       `json:"genre"`
	Director    pgtype.Text    `json:"director"`
	Rating      pgtype.Numeric `json:"rating"`
}
