// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	DeleteMovie(ctx context.Context, id int64) error
	GetMovieByID(ctx context.Context, id int64) (Movie, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
